create or replace view consinco.mflv_basedfitem as
select a.rowid id_df, 'D' tipotabela, 'S' tipnotafiscal,
       b.rowid as id_dfItem,
       a.linkerp,
       a.numerodf, a.seriedf, a.nroserieecf, a.nroempresa,
       a.nrosegmento, nvl(a.seqvendedor,d.nroreppadrao) nrorepresentante,
       a.seqpessoa, a.dtamovimento dtaentrada, a.dtamovimento dtaemissao,
       a.dtahoremissao, a.dtabasevencimento, a.dtavencimento,
       a.dtahorsaida, a.nrocondicaopagto,
       a.nroformapagto, a.prazomediovencto, a.prazoadicional,
       nvl(b.nropedidovenda, a.nropedidovenda) nropedidovenda, a.nropedcliente, a.ufdestino uforigemdestino,
       a.nrobancocobr, a.nrocarteiracobr, a.nroempresacobr, a.seqctacorrente,
       a.nrocarga, a.seqtransportador, a.placaveiculo,
       c.gertitfinanceiro, c.gerlivrofiscal, c.geralteracaoestq,
       c.acmcompravenda, c.geralteracaoestqfisc, c.tipdocfiscal,
       a.observacao, FC5_CGOOBSERVACAOPADRAONF(c.codgeraloper,a.nroempresa) OBSPADRAONF,
       nvl(a.dtalancamento, a.dtamovimento) dtalancamento, a.statusdf,
       a.codgeraloper, b.cfop, b.codtributacao, to_char(b.situacaonf) situacaonf,
       b.seqproduto, b.peraliquotaicms, b.peraliqicmsorig, b.peraliquotaipi,
       b.qtdembalagem, a.indreplicacao,
       b.seqitemdf, b.peraliquotaicmsst,
       b.quantidade quantidade,
       b.vlritem vlrprodbruto,
       b.vlritem,
       nvl(b.vlracrescimo, 0) vlracrescimo,
       nvl(b.vlrdesconto, 0) vlrdesconto,
       nvl(b.vlrdesconto, 0) vlrdescitem,
       (b.vlritem + nvl(b.vlracrescimo, 0) - nvl(b.vlrdesconto, 0)) vlrcontabil,
       b.bascalcicms baseicms,
       nvl(b.vlricms, round((case when b.tipocalcicmsfisci = 25 then -- RP 144194
                     Round(Round((b.bascalcicms * b.peraliquotaicms / 100),2) - Round((b.bascalcicms * b.peraliquotaicms / 100 * nvl(b.peraliqicmsdif,0) / 100),2), 2)
                   when g.uf = 'RJ' and substr(b.situacaonf, -2) = '51' then
                     (b.bascalcicms * b.peraliquotaicms / 100) - nvl(b.vlricmsdiferido, 0)
                 else
                     (b.bascalcicms * b.peraliquotaicms / 100)
               end), 2)) vlricms,
       round(decode(nvl(b.peraliqicmsorig,0),0,0,b.bascalcicms * b.peraliqicmsorig / 100), 2) VLRICMSORIG,
       b.vlrtotisento vlrisento,
       b.vlrtotoutra vlroutra,
       nvl(b.basecalcipi, 0) baseipi,
       nvl(b.vlripi, 0) vlripi,
       nvl(b.basecalcicmsst, 0) baseicmsst,
       nvl(b.vlricmsst, 0) vlricmsst,
       nvl(b.baseicmsantecipado, 0) baseicmsantecipado,
       nvl(b.vlricmsantecipado, 0) vlricmsantecipado,
       b.aliqicmsantecipado aliqicmsantecipado, PERTRIBUTADOANTEC,
       B.VLRTOTISENTOANTEC, B.VLRTOTOUTRAANTEC,
       nvl(b.vlrseguro, 0) vlrseguro,
       nvl(a.vlrfreteterc, 0) vlrfreteterc, nvl(a.vlrbaseicmsfreteterc, 0) vlrbaseicmsfreteterc,
       a.peraliqicmsfreteterc,
       round(a.vlrbaseicmsfreteterc * a.peraliqicmsfreteterc / 100, 2) vlricmsfreteterc,
       a.tipofrete,
       a.pesototbruto pesobrutonf, a.pesototliquido pesoliquidonf,
       a.qtdtotvolume qtdvolumenf, a.especievolume especievolumenf,
       nvl(fmfl_QtdVolumeItem(a.rowid, 'D'), 0) qtdvolumeitem,
       nvl(b.vlrfretetransp, 0) vlrfretetransp,
       /*nvl(b.lancamentost,'O')*/ b.lancamentost lancamentost,
       nvl(b.vlrcofins, 0) vlrcofins, nvl(b.vlrpis, 0) vlrpis,
       nvl(b.vlrdescsuframa, 0) vlrdescsuframa,
       nvl( b.vlrdescsuframaicms, 0 ) vlrdescsuframaicms,
       nvl( b.vlrdescsuframapis, 0 ) vlrdescsuframapis,
       nvl( b.vlrdescsuframacofins, 0 ) vlrdescsuframacofins,
       nvl( b.indsuframado, 'N' ) indsuframado,
       nvl(b.vlrtotisentoipi, 0) vlrisentoipi,
       nvl(b.vlrtotoutraipi, 0) vlroutraipi,
       b.nrorepitem, b.vlrtotcomissao, b.vlrtotcomissaogar,
       nvl(b.statusitem,'V') as STATUSITEM,
       nvl(b.vlrdespntributitem,0) vlrdespntributitem, nvl(b.vlrdesptributitem,0) vlrdesptributitem,
       0 vlrdespforanf, b.seqloteestoque,
       nvl(b.vlrtotiss, 0) as vlriss,
       nvl(b.vlrir, 0) as vlrir,
       nvl(b.vlracrfinanceiro, 0) as vlracrfinanceiro,
       b.seqprodutobase, b.locatuestq, b.qtddevolvida,
       b.percredcalcvpe, b.peraliquotavpe,
       b.vlrvpe, b.vlricmsvpe,
       b.peraliquotatare, b.peraliqicmscalc, b.codtare,
       b.vlricmstare,
       (case when b.tipocalcicmsfisci = 25 and b.peraliqicmscalc is not null then -- RP 144194
               round(Round((b.bascalcicms * nvl(b.peraliqicmscalc, 0) / 100),2) - round((b.bascalcicms * (nvl(b.peraliqicmscalc, 0) / 100) * nvl(b.peraliqicmsdif,0) / 100),2), 2)
             else
               b.vlricmscalc
       end) vlricmscalc,
       b.tipocalcicmsfisci,
       null tipitem, b.vlrdescsf, decode(nvl(f.geradescicms, c.geradescicms), 'F', 0, b.vlrdescicms) vlrdescicms,
       null indpautaicms, b.situacaonfpis, b.situacaonfcofins,
       0 as vlrimpimportexport, a.nfechaveacesso, a.seqnotafiscal,
       a.nfreferencianro, a.nfreferenciaserie, a.modelodf,
       a.seqpessoaend, b.versaoprod versao,
       b.indcreddebicmsopst, b.codrea, 0 vlrdesctransf, nvl(b.vlrdescincondic, 0) vlrdescincond,
       b.seqordemnfe, b.vlrfecp,
       nvl(f.perdescpis, c.perdescpis) perdescpis, nvl(f.perdesccofins, c.perdesccofins) perdesccofins,
       nvl(f.perdescir, c.perdescir) perdescir, nvl(f.perdesccsll, c.perdesccsll) perdesccsll,
       nvL(f.indemiteicms, c.indemiteicms) indemiteicms, nvl(f.indemiteicmsst, c.indemiteicmsst) indemiteicmsst,
       nvl(f.percfatinss, c.percfatinss) percfatinss, nvl(f.percalfunrural, c.percalfunrural) percalfunrural,
       nvl(f.percfatir, c.percfatir) percfatir, nvl(f.percfatpis, c.percfatpis) percfatpis,
       nvl(f.percfatcofins, c.percfatcofins) percfatcofins, nvl(f.percfatcsll, c.percfatcsll) percfatcsll,
       b.vlrdescpis,
       b.vlrdesccofins, b.vlrdescir,
       b.vlrdesccsll, b.vlrdescinss,
       b.vlrdesciss,
       0 vlrfunruralitem,
       fObsItemPedLicit(a.numerodf, a.seriedf, a.nroempresa, b.seqproduto, b.qtdembalagem) ObsItemPedLicit,
       a.vlrindenizacao,
       a.nronsunf,
       b.vlrtotcomissaotele,
       fNroTeleVendaPed(a.numerodf, a.seriedf, a.nroempresa,b.seqproduto, b.qtdembalagem) nrotelevenda,
       nvl(c.descricaonf, c.descricao) as descricaonfcgo,
       b.vlrbaseicmsretido, b.aliqicmsretido, b.vlricmsretido,
       b.bascalcpis,  b.bascalcofins,
       b.peraliquotapis, b.peraliquotacofins,
       b.aliqpiscalc, b.aliqcofinscalc,
       nvl(b.vlrpiscalc, 0) vlrpiscalc,  nvl( b.vlrcofinscalc, 0 ) vlrcofinscalc,
       fObsItemPedVenda(a.numerodf, a.seriedf, a.nroempresa, b.seqproduto, b.qtdembalagem) ObsItemPedVenda,
       fObsItemPedVendaLongStr(a.numerodf, a.seriedf, a.nroempresa, b.seqproduto, b.qtdembalagem) ObsItemPedVendaLongStr,
       fObsItemPedVendaComplLote(a.numerodf, a.seriedf, a.nroempresa, b.seqproduto, b.qtdembalagem) ObsItemPedVendaComplLote,
       fNroPedVendaLicit(a.numerodf, a.seriedf, a.nroempresa, b.seqproduto, b.qtdembalagem) NroPedVendaLicit,
       (case when b.tipocalcicmsfisci in (5, 25) then -- RP 144194
            b.basicmscalc
       else
            null
       end) baseicmscalc,
       (case when b.tipocalcicmsfisci in (5, 25) then -- RP 144194
            b.vlrtotisentocalc
       else
            null
       end) vlrtotisentocalc,
       (case when b.tipocalcicmsfisci in (5, 25) then -- RP 144194
               b.vlrtotoutracalc
             else
               null
       end) vlrtotoutracalc,
       fNroEmpresaPedVenda(A.NUMERODF, A.SERIEDF, A.NROEMPRESA) NroEmpresaPed,
       nvl(B.SITUACAONFIPI,decode(c.tipdocfiscal , 'D', '50', '99')) SITUACAONFIPI,
       b.vlrtotisentost,
       b.vlrtotoutrost,
       b.perisentost,
       b.peroutrost,
       b.basicmsstdistrib, b.vlricmsstdistrib,
       b.basicmsdistrib, b.vlricmsdistrib,
       b.indimpressonf as indimpressonf,
       b.peraliquotafecp,
       b.bascalcfecp, b.vlrtse,
       nvl(b.vlrfreteitemrateio,0) vlrfreteitemrateio,
       null as obsitem,
       nvl(b.indusaprecofixo,'N') indusaprecofixo,
       nvl(f.indvlripidadoadicional, nvl(c.indvlripidadoadicional, 'N')) as indvlripidadoadicional,
       a.especievolume,
       nvl(b.vlricmsoppropdistrib,0) as vlricmsoppropdistrib,
       nvl(b.BASCALCICMSOPPROPRIADISTRIB, 0) as BASCALCICMSOPPROPRIADISTRIB,
       nvl(b.bascalcicmsoppropria,0) as bascalcicmsoppropria,
       a.ufplacaveiculo as ufplacaveiculo,
       c.tipcgo, null seqauxnotafiscal,
       null vlrdescfincalc, b.vlrdescbasecofins,
       b.vlrdescbasepis, b.peraliquotastcargagliq,
       b.indpautast, b.peraliqicmsdif,
       null vlrabatimento,
       b.perdespoperacionalitem as perdespoperacionalitem,
       nvl(b.vlrdespoperacionalitem,0) as vlrdespoperacionalitem,
       a.seqlocalterc,
       nvl(b.vlrtotdespacessoria, 0) vlrdespacessoria,
       b.situacaonforig,
       nvl(b.vlrembpmc, 0) as vlrembpmc,
       nvl(a.indconcdescbaseicms,'N') as indconcdescbaseicms,
       b.tipotabvenda tipotabvenda,
       c.Tipuso, a.ocorrenciadev, b.ocorrenciadevitem,
       a.apporigem,
       case when nvl(a.vlrfrete_maxtransp, 0) > 0  then
          round(a.vlrfrete_maxtransp / FMFL_QTDITEMNFe(a.rowid, 'D'), 4)
       else
            null
       end as vlrfrete_maxtranspitem,
       null pertributado,
       nvl(b.peracrescstajust, b.peracrescst) peracrescst,
       null pertributst,
       null nroadicaodi,
       null seqadicaodi,
       null vlrdescadicaodi,
       round(fValorProdFinalidade(a.rowid, 'D', 'F') / FMFL_QTDITEMNFe(a.rowid, 'D'), 4) vlrfreterateionfe,
       round(fValorProdFinalidade(a.rowid, 'D', 'G') / FMFL_QTDITEMNFe(a.rowid, 'D'), 4) vlrsegurorateionfe,
       round(fValorProdFinalidade(a.rowid, 'D', 'D') / FMFL_QTDITEMNFe(a.rowid, 'D'), 4) vlrdespesarateionfe,
       nvl(b.baseicmspresumido, 0) baseicmspresumido,
       nvl(b.vlricmspresumido, 0) vlricmspresumido,
       b.pericmspresumido pericmspresumido,
       nvl(B.VLREMBDESCRESSARCST,0) as VLREMBDESCRESSARCST,
       TO_CHAR(B.CODPRODUTO) CODPRODUTO,
       nvl(B.VLRDESCPISTRANSF,0) as VLRDESCPISTRANSF,
       nvl(B.VLRDESCCOFINSTRANSF,0) as VLRDESCCOFINSTRANSF,
       NVL(F.INDIMPORTEXPORT, NVL(C.INDIMPORTEXPORT, 'N')) INDIMPORTEXPORT,
       A.SEQNF,
       null SEQNFREF,
       null NFENTFUTURASERIE,
       null NFENTFUTURANRO,
       a.dtacancelamento,
       null nrodeclaraimport,
       a.statusnfe,
       null vlrpautaipi,
       null as tipforitem,
       b.seqmovtoestq,
       NVL(B.VLRDESPESARATEIODANFE,0) AS VLRDESPESARATEIODANFE,
       NVL(B.VLRSEGURORATEIODANFE,0) AS VLRSEGURORATEIODANFE,
       0 vlrdespesaad,
       0 vlrimpostoimport,
       0 vlrsiscomex,
       0 vlriof,
       0 vlrbaseimpostoimport,
       fRetornaDadosVolumeTransp(a.numerodf, a.seriedf, a.nroempresa, a.nroserieecf, b.seqproduto, 'E') EspecieTranspPed,
       fRetornaDadosVolumeTransp(a.numerodf, a.seriedf, a.nroempresa, a.nroserieecf, b.seqproduto, 'Q') QtdVolTranspPed,
       fRetornaDadosVolumeTransp(a.numerodf, a.seriedf, a.nroempresa, a.nroserieecf, b.seqproduto, 'T') VlrUnitVolTranspPed,
       0 as vlrimpimportexporttopo,
       nvl(CASE WHEN NVL(F.INDVLRIPIDADOADICIONAL, NVL(C.INDVLRIPIDADOADICIONAL, 'N')) = 'T'
                     AND NVL(B.SITUACAONFIPI,'50') NOT IN ('50','00')
                    THEN B.VLRIPI
                    when NVL(F.INDVLRIPIDADOADICIONAL, NVL(C.INDVLRIPIDADOADICIONAL, 'N')) = 'S'
                    then B.VLRIPI
                    ELSE 0 END, 0) as vlripiobsadc,
       case when (nvl(f.indemiteicmsst, nvl(c.indemiteicmsst, 'N')) = 'N' OR (nvl(f.indemiteicmsst, nvl(c.indemiteicmsst, 'N')) = 'C' and nvl(i.indcontribicms,'N') = 'S'))
            and fc5_RetIndSituacaoNF_NFe(b.situacaonf, a.nroempresa) in ( 8 ) then
              nvl(b.vlricmsst, 0)
       else
         0
       end vlricmsstoutrosdesp,
       case when nvl(g.indutilcalcfcp, 'N') = 'S' then
         case when (nvl(f.indemiteicmsst, nvl(c.indemiteicmsst, 'N')) = 'N' OR (nvl(f.indemiteicmsst, nvl(c.indemiteicmsst, 'N')) = 'C' and nvl(i.indcontribicms,'N') = 'S'))
              and fc5_RetIndSituacaoNF_NFe(b.situacaonf, a.nroempresa) in ( 8 ) then
                nvl(b.vlrfcpst, 0)
         else
           0
         end
       when nvl(g.indutilcalcfcp, 'N') = 'N' and nvl(fc5maxparametro('FAT_CARGA', a.nroempresa, 'SOMA_VLR_FECP_ACRESCIMO'), 'S') = 'S' then
         nvl(b.vlrfecp, 0)
       else
         0
       end as vlrfecpoutradespnfe,
       null vlrfretedi, null vlrsegurodi,
       null vlrbasevlraduaneiro,
       a.nrocheckout nrocheckout,
       a.nroecf nroecf,
       nvl(b.vlricmsstsubst,0) vlricmsstsubst,
       nvl(b.bascalcicmsstsubst,0) bascalcicmsstsubst,
       a.nroregtributacao, b.nroregtributacao nroregtribitem,
       nvl(f.indfaturaicmsantec, c.indfaturaicmsantec) indfaturaicmsantec,
       b.peraliqicmssimples,
       b.vlricmssimples,
       b.bascalcicmssimples,
       b.vlrdescbonif,
       a.seqvendedor,
       b.indtipodescbonif, e.seqfamilia,
       null nrocarganotabasecupom,
       a.seqpagador,
       a.nroaidf,
       a.pesototliquido,
       a.pesototbruto,
       a.qtdtotvolume,
       b.nrosegitem,
       b.vlrdescincondic,
       b.vlrtotcomissaosup,
       b.vlrtotisento,
       b.vlrtotoutra,
       b.bascalcicms,
       b.basecalcipi,
       b.basecalcicmsst,
       b.vlrtotoutraipi,
       b.vlrtotisentoipi,
       b.peraliqiss,
       b.vlrbaseiss,
       b.vlrtotiss,
       b.versaoprod,
       a.ufdestino,
       /*RC 109366*/
       nvl(B.VLRDESCIPITRANSF,0) as VLRDESCIPITRANSF,
       nvl(B.VLRDESCLUCROTRANSF,0) as VLRDESCLUCROTRANSF,
       b.peraliquotaicmsdif,
       b.basicmsdif,
       b.vlricmsdif,
       b.indtribsaidadevol,
       b.indsomafretetransppedvenda,
       a.vlrfrete_maxtransp,
       a.nrointernoreceb,
       null vlropcontratodesc,
       b.vlrfreteabc,
       null inddevolitem,
       c.Capturacupomfiscal,
       null bascalcfecpdev, null peraliquotafecpdev, null vlrfecpdev,
       b.vlrtotcomissaoger,
       b.percargatribmedia,
       nvl(b.vlrdescverbatransf,0) as vlrdescverbatransf,
       nvl(b.vlrdescdiferencatransf,0) as vlrdescdiferencatransf,
       b.basestctsultent,
       null as origemst,
       b.embalagem,
       b.peraliquotaicmsatac,
       b.basicmsatac,
       b.vlricmsatac,
       nvl(a.inddepositofechado, 'N') as inddepositofechado,
       nvl(a.indreplicanfref, 'N') as indreplicanfref,
       null nrodrawback,
       null indviatransporte,
       null vlrafrmm,
       null indformaimport,
       null sepessoaadencomenda,
       nvl(b.vlricmsoppropria, 0) vlricmsoppropria,
       b.codgeraloper as codgeraloperitem,
       a.indfatcruzado,
       to_number(decode(nvl(f.geradescicms, c.geradescicms), 'F', null, b.indmotivodesoicms)) indmotivodesoicms,
       b.situacaocsosn,
       decode(f.indcontrolaverbasellin, null, decode(c.indcontrolaverbasellin, 'S', b.vlrverbacompra, 0),
                                        'S', b.vlrverbacompra,
                                             0) vlrverbacompra,
       decode(f.indcontrolaverbasellin, null, decode(c.indcontrolaverbasellin, 'S', b.vlrverbabonifincid, 0),
                                        'S', b.vlrverbabonifincid,
                                             0) vlrverbabonifincid,
       decode(f.indcontrolaverbasellin, null, decode(g.indcontrolaverbasellin, 'S', b.vlrverbabonifsemincid, 0),
                                        'S', b.vlrverbabonifsemincid,
                                             0) vlrverbabonifsemincid,
       a.indnfintegrafiscal,
       nvl(b.vlrdespfixatransf,0) as vlrdespfixatransf,
       nvl(b.vlricmstransf, 0) as vlricmstransf,
       nvl(b.vlrdescicmstransf, 0) as vlrdescicmstransf,
       b.indconvertcomponente,
       b.seqprodutofinal,
       b.quantidadeprodfinal,
       nvl(h.indpermsusppiscofins, 'S') indpermsusppiscofins,
       nvl(b.qtdverbapdv, 0) qtdverbapdv,
       nvl(b.vlrverbapdv, 0) vlrverbapdv,
       nvl(b.vlrpiscofinsverbapdv, 0) vlrpiscofinsverbapdv,
       nvl(b.vlrdescfornec, 0) vlrdescfornec,
       b.classeenquadramentoipi,
       b.codigoenquadramentoipi,
       b.codigoseloipi,
       b.qtdseloipi,
       null as MARCAVOLUME,
       null as NUMEROVOLUME,
       b.basecalcicmsstembutprod,
       b.peraliquotaicmsstembutprod,
       b.vlricmsstembutprod,
       nvl(f.geradescicms, c.geradescicms) geradescicms,
       nvl(b.vlrunitarioecf,0) as vlrunitarioecf,
       a.nfedtaenv,
       NVL(b.INDCALCICMSDESONOUTROS,'N') as INDCALCICMSDESONOUTROS,             -- RP 138302
       NVL(b.VLRTOTICMSDESONOUTROS,0) as VLRTOTICMSDESONERADO,                  -- RP 138302
       case when c.tipdocfiscal = 'D' then
           b.INDMOTIVODESOICMS
       else
           decode(b.indcalcicmsdesonoutros, 'S', decode(g.uf, 'RJ', b.INDMOTIVODESOICMS, 9), null)
       end motivodesoneracaoicms,                                                -- RP 138302
       nvl(f.indremessaconsumo, c.indremessaconsumo) indremessaconsumo,
       nvl(f.situacaonfpis, c.situacaonfpis) situacaonfpiscgo,
       nvl(f.situacaonfcofins, c.situacaonfcofins) situacaonfcofinscgo,
       b.vlrunitariodev vlrunitariodev,                                        -- RP 138302
       b.vlricmsantecipadotransf,
       h.codcest,
       0 VLRDESCCONTRATODEV,
       0 PERCDESCCONTRDEV,
       NVL(C.INDCGODEVTRANSF,'N') INDCGODEVTRANSF,
       NVL(C.INDNFBASECUPOM,'N') INDNFBASECUPOM,
       B.BASCALCICMSPARTILHA,
       NVL(B.PERALIQUOTAFECPPARTILHA,0) PERALIQUOTAFCP,
       B.PERALIQINTPARTILHAICMS,
       B.PERPARTILHAICMS,
       NVL(B.VLRFECPPARTILHA,0) VLRFCP,
       B.VLRICMSCALCDESTINO,
       B.VLRICMSCALCORIGEM,
       A.INDCONSUMIDORFINAL,
       B.TIPOCALCICMSPARTILHA,
       B.BASCALCICMSPARTINTEREST,
       B.BASCALCFECPPARTILHA,
       B.PERALIQUOTAFECPPARTILHA,
       B.VLRFECPPARTILHA,
       B.VLRDESCRESTICMSTRANSF,
       B.INDGERADEBCREDPIS,
       B.INDGERADEBCREDCOFINS,
       NULL as INDSUBICMSDESTOTNF,
       NVL(C.INDVENDAINTERPRESENCIAL,'N') INDVENDAINTERPRESENCIAL,
       NVL(F.CFOPESTADO, C.CFOPESTADO) CFOPESTADO,
       b.nfreferencianro nfreferencianro_item, b.nfreferenciaserie nfreferenciaserie_item,
       NVL(B.INDTRANSFCUSTOBONIF, 'N') as INDTRANSFCUSTOBONIF,
       0 VLRDESCCONTRATOGC,
       b.cgoremessa, b.indcomptotnfremessa,
       b.vlricmsopreembolso,
       b.vlricmsstreembolso,
       b.vlricmsreembolso,
       b.peraliquotaicmsstdistrib,
       B.VLRDESCTOSAZONAL,
       B.PERCDESCSAZONAL,
       NVL(b.indsomafreteicms, 'S') indsomafreteicms,
       decode(B.INDGERADEBCREDPIS,null,findcredpiscofins(b.situacaonfpis,'P','C'), B.INDGERADEBCREDPIS) INDGERADEBCREDPISCALC,
       decode(B.INDGERADEBCREDCOFINS,null,findcredpiscofins(b.situacaonfcofins,'C','C'), B.INDGERADEBCREDCOFINS) INDGERADEBCREDCOFINSCALC,
       b.fatorconvipipiscofins FATORCONVIPIPISCOFINS,
       b.vlrminpis VLRMINPIS,
       b.vlrmincofins VLRMINCOFINS,
       b.vlrminipi VLRMINIPI,
       C.INDGERADIFCREDDEBTRANSF, B.VLRRESTCRED,
       b.peraliqicmsdeson, b.CODORIGEMTRIB,
       B.SEQFORMULAFEEF, b.codobservacaodev,
       null as nropedclientenf,
       C.Tipocalculoicms, null as nomedevolucao, null as rgdevolucao,
       B.BASEFCPST,
       B.PERALIQFCPST,
       B.VLRFCPST,
       B.BASEFCPICMS,
       B.PERALIQFCPICMS,
       B.VLRFCPICMS,
       B.BASEFCPDISTRIB,
       B.PERALIQFCPDISTRIB,
       B.VLRFCPDISTRIB,
       B.CODAJUSTEEFD,
       B.PERREDBCICMSEFET,
       B.VLRBASEICMSEFET,
       B.PERALIQICMSEFET,
       B.VLRICMSEFET,
       B.INDESCALARELEVANTE,
       B.CNPJFABRICANTE,
       B.DIGCNPJFABRICANTE,
       0 VLRFRETENANF,
       A.SEQNFREF SEQNFREFDF,
       b.INDDEVOLITEM INDDEVOLITEMDF,
       C.INDNFCOMPREMESSA,
       B.INDSOMAIPIBASEICMS INDSOMAIPIBASEICMS,
       h.codnbmsh,
       a.indreqrecopi,
       a.numerorecopi,
       h.papelimune,
       nvl(b.vlrdesctransfcontgcprecif,0) as vlrdesctransfcontgcprecif,
       nvl(b.vlrdesctransfcontgccomerc,0) as vlrdesctransfcontgccomerc,
       NVL(B.SEQNFREF, A.SEQNFREF) SEQNFREFITEM,
       C.TIPPEDIDOCOMPRA,
       NULL DTARECEBIMENTO,
       nvl(b.vlrdesptributitem, 0) vlrdesptributnf,
       B.VLRIMPOSTOPRESUM,
       B.VLRCUSTOLIQEMP VLRCUSTOLIQEMP,
       null as vlrbasevlradiimp,
       null as vlrbasevlradipi,
       null as vlrbasevlradpis,
       null as vlrbasevlradcofins,
       null as vlrbasevlradicms,
       i.uf ufgepessoa,
       B.BASECARGTRIBMED,
       B.PERDIFERIDO perdiferido,
       B.Vlricmsdiferido,
       nvl(b.indsubtraiicmsdesontotitem, 'S') indsubtraiicmsdesontotitem,
       b.indcalcoutorgado,
       b.tiptributacao,
       nvl(b.indvdaproximovencto, 'N') indvdaproximovencto,
       b.codobservacaoajusteefd,
       nvl(c.Indcomplvlrimp, 'N') Indcomplvlrimp,
       nvl(c.Indnfeajuste, 'N') Indnfeajuste,
       c.indnfrefprodrural,
       null indcontranotanfprodrural,
       null tippedcompraitem,
       null inddesccontratodescfin,
       null indqtdzeradanfcompl,
       null indutilaliqicmssimplesindust,
       b.seqidprescritor,
       b.Nronotificacao AS Notificacaorna,
       b.Dtareceita AS Datarna
from   mfl_doctofiscal a, mfl_dfitem b,
       max_codgeraloper c, mad_parametro d,
       map_produto      e, max_codgeraloper f,
       max_empresa g, map_familia   h, ge_pessoa i
where  b.numerodf        =          a.numerodf
and    b.seriedf         =          a.seriedf
and    b.nroserieecf     =          a.nroserieecf
and    b.nroempresa      =          a.nroempresa
--and    nvl(b.seqnf, nvl(a.seqnf, 0)) = nvl(a.seqnf, 0)
and    (a.seqnf Is Null Or (a.seqnf = b.seqnf))
and    c.codgeraloper    =          a.codgeraloper
and    d.nroempresa      =          a.nroempresa
and    b.seqproduto      =          e.seqproduto
and    b.codgeraloper    =          f.codgeraloper(+)
and    a.nroempresa      =          g.nroempresa
and    h.seqfamilia      =          e.seqfamilia
and    a.seqpessoa       =          i.seqpessoa
union all
select a.rowid id_df, 'N' tipotabela, a.tipnotafiscal tipnotafiscal,
       b.rowid as id_dfItem,
       a.linkerp,
       a.numeronf, a.serienf, 'NF' nroserieecf, a.nroempresa,
       d.nrosegmentoprinc nrosegmento, nvl(b.nrorepresentante, e.nroreppadrao),
       a.seqpessoa, a.dtaentrada, a.dtaemissao,
       a.dtaemissao dtahoremissao, a.dtaemissao dtabasevencimento, null dtavencimento,
       a.dtasaida dtahorsaida, a.nrocondpagto nrocondicaopagto,
       a.nroformapagto, 0 prazomediovencto, 0 prazoadicional,
       null nropedidovenda, null nropedcliente, a.uforigemdestino uforigemdestino,
       null nrobancocobr, null nrocarteiracobr, null nroempresacobr, null seqctacorrente,
       a.nrointernoreceb nrocarga, a.seqtransportador, a.placatransp placaveiculo,
       c.gertitfinanceiro, c.gerlivrofiscal, c.geralteracaoestq,
       c.acmcompravenda, c.geralteracaoestqfisc, c.tipdocfiscal,
       a.observacao, FC5_CGOOBSERVACAOPADRAONF(c.codgeraloper, a.nroempresa) OBSPADRAONF,
       a.dtaemissao dtalancamento, a.statusnf statusdf,
       a.codgeraloper, b.cfop, b.codtributacao, to_char(b.situacaonf) situacaonf,
       b.seqproduto, b.peraliquotaicms, b.peraliqicmsorig, b.peraliquotaipi,
       b.qtdembalagem, a.indreplicacao,
       b.seqitemnf seqitemdf, b.peraliquotaicmsst,
       b.quantidade quantidade,
       b.vlritem vlrprodbruto,
       b.vlritem,
       (case when a.indconsidfretedesptrib = 'N' then
                         b.vlrdesptributitem + nvl(b.vlrfretenanf,0)
                    else
                         b.vlrdesptributitem
                    end + nvl(b.vlrdespntributitem, 0) +
        nvl(b.vlripi, 0) + nvl(b.vlricmsst, 0) +
        decode(nvl(a.indimportexport,'N')||nvl(a.indtotnfigualbicms,'N'),'SN',nvl(b.vlricms,0),0) +
        nvl(b.vlrfcpst, 0)) vlracrescimo,
       (nvl(b.vlrdescitem, 0) + nvl(b.vlrdescsuframa, 0)) vlrdesconto,
       nvl(b.vlrdescitem, 0) vlrdescitem,
       (b.vlritem + case when a.indconsidfretedesptrib = 'N' then
                         b.vlrdesptributitem + nvl(b.vlrfretenanf,0)
                    else
                         b.vlrdesptributitem
                    end + b.vlrdespntributitem + b.vlripi +
            decode(nvl(b.lancamentost, 'C'), 'O', 0, 'S',0, b.vlricmsst) -
            b.vlrdescitem - nvl(b.vlrdescsuframa, 0) +
            decode(nvl(b.lancamentost, 'C'), 'O', 0, 'S', 0, nvl(b.vlrfcpst, 0))
       ) vlrcontabil,
       b.Bascalcicms baseicms,
       (case when b.tipocalcicmsfisci = 25 and b.peraliqicmsdif > 0 and a.apporigem in (22,39) then
           Round(Round((b.bascalcicms * b.peraliquotaicms / 100),2) - round((b.bascalcicms * b.peraliquotaicms / 100 * b.peraliqicmsdif / 100),2), 2)
         else
             b.vlricms
       end) vlricms,
       round(decode(nvl(b.peraliqicmsorig,0),0,0,b.bascalcicms * b.peraliqicmsorig / 100), 2) vlricmsorig,
       b.vlrtotisento vlrisento,
       b.vlrtotoutra vlroutra,
       nvl(b.bascalcipi, 0) baseipi,
       nvl(b.vlripi, 0) vlripi,
       nvl(b.bascalcicmsst, 0) baseicmsst,
       nvl(b.vlricmsst, 0) vlricmsst,
       nvl(b.baseicmsantecipado, 0) baseicmsantecipado,
       nvl(b.vlricmsantecipado, 0) vlricmsantecipado,
       b.pericmsantecipado aliqicmsantecipado, PERTRIBUTADOANTEC,
       B.VLRTOTISENTOANTEC, B.VLRTOTOUTRAANTEC,
       nvl(b.vlrseguro, 0) vlrseguro,
       nvl(0, 0) vlrfreteterc, nvl(0, 0) vlrbaseicmsfreteterc,
       0 peraliqicmsfreteterc,
       0 vlricmsfreteterc,
       a.tipfretetransp tipofrete,
       a.pesototbruto pesobrutonf, a.pesototliquido pesoliquidonf,
       a.qtdtotvolume qtdvolumenf, a.especievolume especievolumenf,
       nvl(a.qtdtotvolume,0) qtdvolumeitem,
       nvl(b.vlrfrete, 0) vlrfretetransp,
       b.lancamentost,
       nvl(b.vlrcofins, 0) vlrcofins, nvl(b.vlrpis, 0) vlrpis,
       nvl( b.vlrdescsuframa, 0 ) vlrdescsuframa,
       nvl( b.vlrdescsuframaicms, 0 ) as vlrdescsuframaicms,
       nvl( b.vlrdescsuframapis, 0 ) as vlrdescsuframapis,
       nvl( b.vlrdescsuframacofins, 0 ) as vlrdescsuframacofins,
       nvl(b.indsuframado,'N') indsuframado,
       nvl(b.vlrtotisentoipi, 0) vlrisentoipi,
       nvl(b.vlrtotoutraipi, 0) vlroutraipi,
       b.nrorepresentante nrorepitem, b.vlrtotcomissao, b.vlrtotcomissaogar,
       nvl(a.statusnf,'V') as STATUSITEM,
       nvl(b.vlrdespntributitem, 0) vlrdespntributitem,  nvl(b.vlrdesptributitem, 0) vlrdesptributitem,
       b.vlrdespforanf, b.seqloteestoque,
       nvl(b.vlrtotiss, 0) as vlriss,
       nvl(b.vlrir, 0) as vlrir,
       nvl(0, 0) as vlracrfinanceiro,
       b.seqprodutobase, b.locatuestq, b.qtddevolvida,
       b.percredcalcvpe, b.peraliquotavpe,
       b.vlrvpe, b.vlricmsvpe,
       b.peraliquotatare, b.peraliquotaicmscalc, b.codtare,
       b.vlricmstare,
       b.vlricmscalc, b.tipocalcicmsfisci,
       b.tipitem, b.vlrdescsf,
       decode(c.geradescicms, 'F', 0, NVL(b.vlrdescicms,0)) + case when (a.tipnotafiscal = 'S' or c.tipuso = 'E') and nvl(a.indsubicmsdestotnf,'S') = 'S' then
                                                                 NVL(b.VLRTOTICMSDESONERADO, 0)
                                                              else
                                                                 0
                                                              end vlrdescicms,
       b.indpautaicms, b.situacaonfpis, b.situacaonfcofins,
       nvl(b.vlrimpimportexport, 0), a.nfechaveacesso, a.seqnotafiscal,
       b.nfreferencianro, b.nfreferenciaserie, a.modelonf,
       a.enderecoentrega seqpessoaend, b.versao versao,
       b.indcreddebicmsopst, b.codrea, b.vlrdesctransf,
       nvl(b.vlrdescincond,0) as vlrdescincond,
       b.seqordemnfe, b.vlrfecp,
       c.perdescpis, c.perdesccofins,
       c.perdescir, c.perdesccsll,
       c.indemiteicms, c.indemiteicmsst,  c.percfatinss,
       c.percalfunrural, c.percfatir,
       c.percfatpis, c.percfatcofins, c.percfatcsll,
       b.vlrdescpis,
       b.vlrdesccofins, b.vlrdescir,
       b.vlrdesccsll, b.vlrdescinss,
       b.vlrdesciss,
       nvl(b.vlrfunruralitem, 0) vlrfunruralitem,
       null ObsItemPedLicit,
       0 vlrindenizacao,
       a.nronsunf,
       b.vlrtotcomissaotele,
       fNroTeleVendaPed(a.nfreferencianro, a.nfreferenciaserie, a.nroempresa, b.seqproduto, b.qtdembalagem) nrotelevenda,
       nvl(c.descricaonf, c.descricao) as descricaonfcgo,
       b.vlrbaseicmsretido, b.aliqicmsretido, b.vlricmsretido,
       b.bascalcpis,  b.bascalcofins,
       b.peraliquotapis, b.peraliquotacofins,
       b.aliqpiscalc, b.aliqcofinscalc,
       nvl( b.vlrpiscalc, 0 ) vlrpiscalc, nvl( b.vlrcofinscalc, 0 ) vlrcofinscalc,
       null ObsItemPedVenda,
       null ObsItemPedVendaLongStr,
       null ObsItemPedVendaComplLote,
       null NroPedVendaLicit,
       b.baseicmscalc, b.vlrtotisentocalc, b.vlrtotoutracalc,
       NULL NroEmpresaPed,
    -- nvl(B.SITUACAONFIPI,DECODE(A.Tipnotafiscal, 'E', '00',decode(c.tipdocfiscal, 'D', '50', '99'))) SITUACAONFIPI,
       nvl(B.SITUACAONFIPI,DECODE(C.TIPUSO,'R',null,DECODE(A.Tipnotafiscal, 'E', '00',decode(c.tipdocfiscal, 'D', '50', null)))) SITUACAONFIPI,
       b.vlrtotisentost,
       b.vlrtotoutrost,
       b.perisentost,
       b.peroutrost,
       b.basicmsstdistrib, b.vlricmsstdistrib,
       b.basicmsdistrib, b.vlricmsdistrib,
       null as indimpressonf,
       b.peraliquotafecp,
       b.bascalcfecp, b.vlrtse,
       nvl(b.vlrfreteitemrateio,0) vlrfreteitemrateio,
       nvl(f.observacao, b.OBSERVACAO) as obsitem,
       'N' indusaprecofixo,
       nvl(c.indvlripidadoadicional, 'N') as indvlripidadoadicional,
       a.especievolume,
       nvl(b.vlricmsoppropdistrib,0) as vlricmsoppropdistrib,
       0 BASCALCICMSOPPROPRIADISTRIB,
       nvl(b.bascalcicmsoppropria,0) as bascalcicmsoppropria,
       a.ufplacatransp as ufplacaveiculo,
       c.tipcgo, a.seqauxnotafiscal,
       b.vlrdescfincalc, b.vlrdescbasecofins,
       b.vlrdescbasepis, b.peraliquotastcargagliq,
       b.indpautast, b.peraliqicmsdif,
       b.vlrabatimento,
       b.perdespoperacionalitem as perdespoperacionalitem,
       nvl(b.vlrdespoperacionalitem,0) as vlrdespoperacionalitem,
       b.seqlocalterc,
       0 as vlrdespacessoria,
       b.situacaonforig,
       nvl(b.vlrembpmc, 0) as vlrembpmc,
       nvl(a.indconcdescbaseicms,'N') as indconcdescbaseicms,
       null tipotabvenda,
       c.Tipuso, a.ocorrenciadev, b.ocorrenciadevitem,
       a.apporigem,
       null vlrfrete_maxtranspitem,
       b.pertributado,
       b.peracrescst,
       b.pertributst,
       b.nroadicaodi,
       b.seqadicaodi,
       b.vlrdescadicaodi,
       round(fValorProdFinalidade(a.rowid, 'N', 'F') / FMFL_QTDITEMNFe(a.rowid, 'N'), 4) vlrfreterateionfe,
       round(fValorProdFinalidade(a.rowid, 'N', 'G') / FMFL_QTDITEMNFe(a.rowid, 'N'), 4) vlrsegurorateionfe,
       round(fValorProdFinalidade(a.rowid, 'N', 'D') / FMFL_QTDITEMNFe(a.rowid, 'N'), 4) vlrdespesarateionfe,
       nvl(b.baseicmspresumido, 0) baseicmspresumido,
       nvl(b.vlricmspresumido, 0) vlricmspresumido,
       b.pericmspresumido pericmspresumido,
       nvl(B.VLREMBDESCRESSARCST,0) AS VLREMBDESCRESSARCST,
       TO_CHAR(B.SEQPRODUTO) as CODPRODUTO,
       0 as VLRDESCPISTRANSF,
       0 as VLRDESCCOFINSTRANSF,
       NVL(C.INDIMPORTEXPORT, 'N') INDIMPORTEXPORT,
       A.SEQNF,
       B.SEQNFREF,
       B.NFENTFUTURASERIE,
       B.NFENTFUTURANRO,
       a.dtacancelamento,
       a.nrodeclaraimport,
       a.statusnfe,
       nvl(b.vlrpautaipi,0) vlrpautaipi,
       case when a.apporigem in (22,39) and b.situacaonf = '070' and b.tipforitem is null and b.nfreferencianro is not null then
           fc5BuscaTipoFornecItem(b.nroempresa, b.seqproduto, b.seqnfref, b.nfreferencianro, b.nfreferenciaserie)
       else
         b.tipforitem
       end   as tipforitem,
       b.seqmovtoestq,
       0 AS VLRDESPESARATEIODANFE,
       0 AS VLRSEGURORATEIODANFE,
       nvl(b.vlrdespesaad, 0) as vlrdespesaad,
       nvl(b.vlrimpostoimport, 0) as vlrimpostoimport,
       nvl(b.vlrsiscomex, 0) as vlrsiscomex,
       0 vlriof,
       nvl(b.vlrbaseimpostoimport, 0) as vlrbaseimpostoimport,
       null EspecieTranspPed,
       null QtdVolTranspPed,
       null VlrUnitVolTranspPed,
       nvl(a.vlrimpimportexport, 0) as vlrimpimportexporttopo,
       nvl(CASE WHEN NVL(C.INDVLRIPIDADOADICIONAL, 'N') = 'T'
                     AND NVL(B.SITUACAONFIPI,DECODE(A.TIPNOTAFISCAL,'E','00','50')) NOT IN ('50','00')
                    THEN B.VLRIPI
                    WHEN NVL(C.INDVLRIPIDADOADICIONAL, 'N') = 'S'
                    THEN B.VLRIPI
                    ELSE 0 END, 0) as vlripiobsadc,
       ( case when (nvl(c.indemiteicmsst,'N') = 'N' OR (nvl(c.indemiteicmsst,'N') = 'C' and nvl(i.indcontribicms,'N') = 'S'))
              and c.tipcgo || c.tipuso || c.tipdocfiscal != 'E' || 'E' || 'C'
              and fc5_RetIndSituacaoNF_NFe(b.situacaonf, a.nroempresa) in ( 8 ) then
                nvl(b.vlricmsst, 0)
         else
           0
         end
       ) vlricmsstoutrosdesp,
       case when nvl(d.indutilcalcfcp, 'N') = 'S' then
         case when (nvl(c.indemiteicmsst, 'N') = 'N' OR (nvl(c.indemiteicmsst, 'N') = 'C' and nvl(i.indcontribicms, 'N') = 'S'))
              and c.tipcgo || c.tipuso || c.tipdocfiscal != 'E' || 'E' || 'C'
              and fc5_RetIndSituacaoNF_NFe(b.situacaonf, a.nroempresa) in ( 8 ) then
                nvl(b.vlrfcpst, 0)
         else
           0
         end
       when nvl(d.indutilcalcfcp, 'N') = 'N' and nvl(fc5maxparametro('FAT_CARGA', a.nroempresa, 'SOMA_VLR_FECP_ACRESCIMO'), 'S') = 'S' then
         nvl(b.vlrfecp, 0)
       else
         0
       end as vlrfecpoutradespnfe,
       b.vlrfretedi, b.vlrsegurodi,
       b.vlrbasevlraduaneiro vlrbasevlraduaneiro,
       null nrocheckout,
       null nroecf,
       nvl(b.vlricmsstsubst,0) vlricmsstsubst,
       nvl(b.bascalcicmsstsubst,0) bascalcicmsstsubst,
       a.nroregtributacao, b.nroregtributacao nroregtribitem,
       c.indfaturaicmsantec,
       b.peraliqicmssimples peraliqicmssimples,
       b.vlricmssimples vlricmssimples,
       b.bascalcicmssimples,
       0 vlrdescbonif,
       0 seqvendedor,
       null indtipodescbonif, g.seqfamilia,
       a.nrocargaexped nrocarganotabasecupom,
       a.seqpagador,
       a.nroaidf,
       a.pesototliquido,
       a.pesototbruto,
       a.qtdtotvolume,
       b.nrosegitem,
       0 vlrdescincondic,
       b.vlrtotcomissaosup,
       b.vlrtotisento,
       b.vlrtotoutra,
       b.bascalcicms,
       b.bascalcipi,
       b.bascalcicmsst,
       b.vlrtotoutraipi,
       b.vlrtotisentoipi,
       b.peraliqiss,
       b.vlrbaseiss,
       b.vlrtotiss,
       b.versao,
       null ufdestino,
       /*RC 109366*/
       0 as VLRDESCIPITRANSF,
       0 as VLRDESCLUCROTRANSF,
       b.peraliquotaicmsdif,
       b.basicmsdif,
       b.vlricmsdif,
       null indtribsaidadevol,
       'N' indsomafretetransppedvenda,
       null vlrfrete_maxtransp,
       a.nrointernoreceb,
       b.vlropcontratodesc,
       b.vlrfreteabc,
       b.inddevolitem,
       c.Capturacupomfiscal,
       b.bascalcfecpdev, b.peraliquotafecpdev, b.vlrfecpdev,
       b.vlrtotcomissaoger,
       b.percargatribmedia,
       nvl(b.vlrdescverbatransf,0) as vlrdescverbatransf ,
       nvl(b.vlrdescdiferencatransf,0) as vlrdescdiferencatransf ,
       b.basestctsultent,
       b.origemst,
       b.embalagem,
       b.peraliquotaicmsatac,
       b.basicmsatac,
       b.vlricmsatac,
       nvl(a.inddepositofechado, 'N') as inddepositofechado,
       'N' as indreplicanfref,
       b.nrodrawback,
       a.indviatransporte,
       a.vlrafrmm,
       a.indformaimport,
       a.sepessoaadencomenda,
       nvl(b.vlricmsoppropria, 0) vlricmsoppropria,
       null as codgeraloperitem, null,
       NVL(to_number(decode(c.geradescicms, 'F', null, b.indmotivodesoicms)), b.MOTIVODESONERACAOICMS) indmotivodesoicms,
       b.situacaocsosn,
       decode(c.indcontrolaverbasellin, 'S', b.vlrverbacompra, 0) vlrverbacompra,
       decode(c.indcontrolaverbasellin, 'S', b.vlrverbabonifincid, 0) vlrverbabonifincid,
       decode(c.indcontrolaverbasellin, 'S', b.vlrverbabonifsemincid, 0) vlrverbabonifsemincid,
       a.indnfintegrafiscal,
       null vlrdespfixatransf,
       0 as vlricmstransf,
       0 as vlrdescicmstransf,
       b.indconvertcomponente,
       b.seqprodutofinal,
       b.quantidadeprodfinal,
       nvl(h.indpermsusppiscofins, 'S') indpermsusppiscofins,
       nvl(b.qtdverbapdv, 0) qtdverbapdv,
       nvl(b.vlrverbapdv, 0) vlrverbapdv,
       nvl(b.vlrpiscofinsverbapdv, 0) vlrpiscofinsverbapdv,
       nvl(b.vlrdescfornec, 0) vlrdescfornec,
       null classeenquadramentoipi,
       null codigoenquadramentoipi,
       null codigoseloipi,
       null qtdseloipi,
       A.MARCAVOLUME,
       A.NUMEROVOLUME,
       b.basecalcicmsstembutprod,
       b.peraliquotaicmsstembutprod,
       b.vlricmsstembutprod,
       c.geradescicms geradescicms,
       b.vlrunitarioecf,
       a.nfedtaenv,
       nvl(b.INDCALCICMSDESONOUTROS, 'N')  as INDCALCICMSDESONOUTROS,             -- RP 138302
       nvl(b.VLRTOTICMSDESONERADO, 0)      as VLRTOTICMSDESONERADO,               -- RP 138302
       b.MOTIVODESONERACAOICMS,                                                   -- RP 138302
       c.indremessaconsumo,
       c.situacaonfpis situacaonfpiscgo,
       c.situacaonfcofins situacaonfcofinscgo,
       b.vlrunitariodev vlrunitariodev,                                                   -- RP 138302
       null vlricmsantecipadotransf,
       h.codcest,
       B.VLRDESCCONTRATODEV,
       B.PERCDESCCONTRDEV,
       NVL(C.INDCGODEVTRANSF,'N') INDCGODEVTRANSF,
       NVL(C.INDNFBASECUPOM,'N') INDNFBASECUPOM,
       B.BASCALCICMSPARTILHA,
       NVL(B.PERALIQUOTAFECPPARTILHA,0) PERALIQUOTAFCP,
       B.PERALIQINTPARTILHAICMS,
       B.PERPARTILHAICMS,
       NVL(B.VLRFECPPARTILHA,0) VLRFCP,
       B.VLRICMSCALCDESTINO,
       B.VLRICMSCALCORIGEM,
       A.INDCONSUMIDORFINAL,
       B.TIPOCALCICMSPARTILHA,
       B.BASCALCICMSPARTINTEREST,
       B.BASCALCFECPPARTILHA,
       B.PERALIQUOTAFECPPARTILHA,
       B.VLRFECPPARTILHA,
       B.VLRDESCRESTICMSTRANSF,
       B.INDGERADEBCREDPIS,
       B.INDGERADEBCREDCOFINS,
       A.INDSUBICMSDESTOTNF,
       NVL(C.INDVENDAINTERPRESENCIAL,'N') INDVENDAINTERPRESENCIAL,
       C.CFOPESTADO,
       b.nfreferencianro nfreferencianro_item, b.nfreferenciaserie nfreferenciaserie_item,
       null as INDTRANSFCUSTOBONIF,
       NVL(B.VLRDESCCONTRATOGC, 0) VLRDESCCONTRATOGC,
       b.cgoremessa, b.indcomptotnfremessa,
       b.vlricmsopreembolso,
       b.vlricmsstreembolso,
       b.vlricmsreembolso,
       b.peraliquotaicmsstdistrib,
       B.VLRDESCTOSAZONAL,
       B.PERCDESCSAZONAL,
       'N' indsomafreteicms,
       decode(B.INDGERADEBCREDPIS,null,findcredpiscofins(b.situacaonfpis,'P','C'), B.INDGERADEBCREDPIS) INDGERADEBCREDPISCALC,
       decode(B.INDGERADEBCREDCOFINS,null,findcredpiscofins(b.situacaonfcofins,'C','C'), B.INDGERADEBCREDCOFINS) INDGERADEBCREDCOFINSCALC,
       null FATORCONVIPIPISCOFINS,
       null VLRMINPIS,
       null VLRMINCOFINS,
       null VLRMINIPI,
       C.INDGERADIFCREDDEBTRANSF, B.VLRRESTCRED,
       null peraliqicmsdeson, B.CODORIGEMTRIB,
       B.SEQFORMULAFEEF, b.codobservacaodev,
       a.nropedcliente nropedclientenf,
       C.Tipocalculoicms, a.nomedevolucao, a.rgdevolucao,
       B.BASEFCPST,
       B.PERALIQFCPST,
       B.VLRFCPST,
       B.BASEFCPICMS,
       B.PERALIQFCPICMS,
       B.VLRFCPICMS,
       B.BASEFCPDISTRIB,
       B.PERALIQFCPDISTRIB,
       B.VLRFCPDISTRIB,
       B.CODAJUSTEEFD,
       B.PERREDBCICMSEFET,
       B.VLRBASEICMSEFET,
       B.PERALIQICMSEFET,
       B.VLRICMSEFET,
       B.INDESCALARELEVANTE,
       B.CNPJFABRICANTE,
       B.DIGCNPJFABRICANTE,
       B.VLRFRETENANF,
       null SEQNFREFDF,
       B.INDDEVOLITEM INDDEVOLITEMDF,
       C.INDNFCOMPREMESSA,
       B.INDSOMAIPIBASEICMS INDSOMAIPIBASEICMS,
       h.codnbmsh,
       a.indreqrecopi,
       a.numerorecopi,
       h.papelimune,
       nvl(b.vlrdesctransfcontgcprecif,0) as vlrdesctransfcontgcprecif,
       nvl(b.vlrdesctransfcontgccomerc,0) as vlrdesctransfcontgccomerc,
       NVL(B.SEQNFREF, A.SEQNFREF) SEQNFREFITEM,
       C.TIPPEDIDOCOMPRA,
       A.DTARECEBIMENTO,
       case when a.indconsidfretedesptrib = 'N' then
         b.vlrdesptributitem + nvl(b.vlrfretenanf,0)
       else
         b.vlrdesptributitem
       end as vlrdesptributnf,
       B.VLRIMPOSTOPRESUM,
       null VLRCUSTOLIQEMP,
       NVL(B.vlrbasevlradiimp,0) vlrbasevlradiimp,
       NVL(B.vlrbasevlradipi,0) vlrbasevlradipi,
       NVL(B.vlrbasevlradpis,0) vlrbasevlradpis,
       NVL(B.vlrbasevlradcofins,0) vlrbasevlradcofins,
       NVL(B.vlrbasevlradicms,0) vlrbasevlradicms,
       i.uf ufgepessoa,
       B.BASECARGTRIBMED,
       B.PERDIFERIDO PERDIFERIDO,
       b.vlricmsdiferido Vlricmsdiferido,
       NVL(a.indsubicmsdestotnf, 'S') as indsubtraiicmsdesontotitem,
       b.indcalcoutorgado,
       null tiptributacao,
       nvl(b.indvdaproximovencto, 'N') indvdaproximovencto,
       null as codobservacaoajusteefd,
       nvl(c.Indcomplvlrimp, 'N') Indcomplvlrimp,
       nvl(c.Indnfeajuste, 'N') Indnfeajuste,
       c.indnfrefprodrural,
       a.indcontranotanfprodrural,
       b.tippedcompraitem,
       b.inddesccontratodescfin,
       b.indqtdzeradanfcompl,
       b.indutilaliqicmssimplesindust,
       null seqidprescritor,
       null as Notificacaorna,
       null as Datarna
from   mlf_notafiscal a, mlf_nfitem b,
       max_codgeraloper c, max_empresa d,
       mad_parametro e, mlf_nfitemobs f,
       map_produto      g, map_familia   h,
       ge_pessoa        i
where  b.numeronf        =          a.numeronf
and    b.serienf         =          a.serienf
and    b.seqpessoa       =          a.seqpessoa
and    b.nroempresa      =          a.nroempresa
and    b.tipnotafiscal   =          a.tipnotafiscal
--and    nvl(b.seqnf, nvl(a.seqnf, 0)) = nvl(a.seqnf, 0)
and    (a.seqnf Is Null Or (a.seqnf = b.seqnf))
and    c.codgeraloper    =          a.codgeraloper
and    d.nroempresa      =          a.nroempresa
and    e.nroempresa      =          a.nroempresa
and    b.seqproduto      =          g.seqproduto
and    h.seqfamilia      =          g.seqfamilia
and    b.numeronf        =        f.numeronf(+)
and    b.seqpessoa       =        f.seqpessoa(+)
and    b.serienf         =        f.serienf(+)
and    b.tipnotafiscal   =        f.tipnotafiscal(+)
and    b.nroempresa      =        f.nroempresa(+)
and    b.seqproduto      =        f.seqproduto(+)
and    b.tipitem         =        f.tipitem(+)
and    b.seqitemnf       =        f.seqitemnf(+)
and    a.seqpessoa       =          i.seqpessoa
;
